# -*- coding: utf-8 -*-
"""
Created on Sun Apr 29 15:31:21 2018

@author: Prongs
"""

def positionofmotif(s,t):
    l=len(t)
    k=[]
    for i in range(len(s)-l):
        if(s[i:i+l]==t):
            k.append(i+1)
    return k
s="GGCACCGCCCGCACCGCCCTCACCGCCCACACCGCCAATGCACCGCCCACCGCCCACCGCCTTGCACCGCCATCTCACCGCCCCACCGCCCACACCGCCAGATATTCTAGACTCACCGCCGCCACCGCCACACACCGCCATTCATCACCGCCGCACCGCCACAAGACACCGCCTCCATCCACCGCCCCACCGCCGGTCACCGCCCGGCACCGCCCACCGCCCCTCACCGCCAGCAGCACCGCCAACACCGCCCTGGCACCGCCCACCGCCCACCGCCGCGCCACCGCCCCACCGCCTTTTGAACACACCGCCATTTGAGCTTTCGGACACCGCCCGGCACCGCCAACACCGCCTCCCACCGCCGTAAGCGACCCACCGCCGCACCGCCGCACCGCCGGGGACCACCGCCCCACCGCCCACCGCCCTAACACCGCCATGCACCGCCCTCCCCCACCGCCACACCGCCAGGCACCGCCGCACCGCCTACACCGCCGCACCGCCTACAAGGAAGCCGGCTTTCTCTTCACCGCCCCACCGCCGAGGGCCACCGCCGAAAAACACCGCCTTACGGCACCGCCCACCGCCCACCGCCGACACCGCCGCACGACACCGCCCACCGCCCACCGCCGGCACCGCCCACCGCCCACCGCCACCACCGCCCGGTCACACCGCCAATCGGTGCACCGCCCTCACCGCCCTGTCACCGCCTGCTTCACCGCCAGCACCGCCTCGGCACCGCCCACCGCCGCCGCACCGCCACACCGCCGCCTGGCACACCGCCATGTACACCGCCACACCGCCTCACCGCCTCACCGCCCACCGCCTGGGCACCGCCGCACCGCCCACCGCCATTCCCACCGCCCTACACCGCCCACCGCCCACCGCCTCACCGCCGGGGGCACCGCC"
t="CACCGCCCA"
print(positionofmotif(s,t))