# -*- coding: utf-8 -*-
"""
Created on Sat Apr 28 11:44:34 2018

@author: Prongs
"""

def Complement(text):
    clt=""
    for i in range(len(text)):
        if(text[i]=='A'):
            clt=clt+'T'
        elif(text[i]=='T'):
            clt=clt+'A'
        elif(text[i]=='G'):
            clt=clt+'C'
        else:
            clt=clt+'G'
    return clt

def Reverse(text):
    rev=""
    l=len(text)
    for i in range(l):
        rev=rev+text[l-i-1]
    return rev

t="ACTAGCAGAGAATCTAATCCGAGGTGTGACTCTCACTTTTGTATAGGGATGTCAGTTCATCGAGAACTGGTCCTCGGTTATTATAGGTGACCGATAATCCGTCGGGGATATCAAGACCGCTATTCGACTCGAGCGTTGGCCTATGGTAGTCAGGCTGGCAGACACTCCTGCTAGTATAGTATTATTACAATGAGTCGCTGATCCGACAGTACTTCCGCACACAAGCAGATGGCAGCAAAATAATCGTAACGAGCACAGTAGCACTTCCAAAGCTTGGAGCTCAAACCACCATCCCCAGGATGGGTTTGCAAGGGAAAATGTAGTATAAATGGCGTATCCCAGGCTGCTCCCAACGCCTTAGGCTATTAGAACGGAACGCTCTTGCCTAAACCCGCCTGACCTGGCACCCTACCAAGACATTCTTGAAAGTGCGATTAGTCTGGTACTAAGACACGTTTAAATTCTAGGAACCATAAAATCGGCTTCCCATAGGTGAGGGGGAAGGCCCTGACGTCGAGTGAATCAGCCACGACAATGTTCGACGGTTTCTGTGCTCGAGTGTACTTATATAAGTACAACTGCCACTTGCGAGTTCTTTTTTCCTGCCGTAAACCGGTGAAGGTACAACATGCCTTGAGGGTCGCGACGGACAACCCGCACTACTGGCGCCCGTAGTACGTCGTTAGTCAGCGAATTGGTGCGGAGTCGTTCGACCGTTCACTACTCCGAATGCCCTATGCACGGTTAGTCCTACCACACGAATAGCGGATGCCCTTGATAGCCGTGTGGCCAGTCGCCTCCAACCCGTAAAGCCGGGGTCGTACAGCTGTGACACGAGCGTGCGAAGACAAACATTAATTTGGCGTGATTGTCGCCCTCTTGGTCGACATTGGTATCGAAAAATGGTCTCAAGGTTGTGTGCCGACGAGGCCTCTACTTAGTACCTAAATGTCAGTGACTGGCCAAATGTAACTCTAGTACGAGCGCTTGTTGC"
print(Reverse(Complement(t)))