# -*- coding: utf-8 -*-
"""
Created on Sat Apr 28 11:24:30 2018

@author: Prongs
"""

def Transcription(text):
    length=len(text)
    mRNA=""
    for i in range(length):
        if(text[i]=='T'):
            mRNA=mRNA+'U'
        else:
            mRNA=mRNA+text[i]    
    return mRNA

t="TCATACTTAACAAGGAAAACACTACCGGAATCGCGCATAATAAAATAGTCGAGAGGTTTGGGAAGATAGTCTGCCCGACGGCTTCCTACCCTACGCGCCGGTGGGCCCGTACTTCTTACCCTTAAAGGGGGCGAGTCTAAAGGTTACTGGCACTGACTGGAACATGAGCCGCGGGAACTTCGCCGAACCCTTGTAATAAAAATTGCTAGCGTGTCGGTAAAAGACGACTGATGCGTTCGCTTCCATATATCAGATCGACTCTCGGTACCGGGGACCTCGCCTGAGATTGTTACCGATGCACCTCGCACTCCGGACTAACAATAAGGAACCCGAAACTCAGTATGTGCTTAAATAAGTAGTTTCTAAAGGTGTGACACCGTCTGGTGGCCAGGGAAGTCACAGTGTTTCAACGCTATTCAGAATGTCGGCTCGGGAGAGGTCATACACGCCAGCCTTAGAACTTCACTGAAATCTGACTGGGTTAGTGTGGGCAATCAGGCCGGCACTTAAATCTTCAATCACTGATTACGCTTATTTGCTCCACGCGACCGGCCGGTGGTAATGGTATTATTTAAGCGTGCTAGGGGATTTAAATGACAGAACGATAGCGTTTGCCACCTTAGCAGGCCCGAAGCTCATACACCGTATTCTCGCGTCACTCAACAACAGACAGCGGCTCTCTCCACGGCACAATCCCTCGGGCCTTGCCTCACGCATAGGCAATAATGTGTGTCCAACACTTAGCCTTAGCTTCGGGAGCGTTTTGAGCCGCAAAGAAATCTATTGCCGAAAGACAGAACAGCTAGATCCGCGCGTTGCCGCCCGAGAGGTAGCAGTCATTTTCTTATGTAAGAACGTGCCATCCATAGTCACTACGGTTTGACTCTTTTATGCCTACATATAGTAACCTCTGGGGGGATGTCTAATAACGGGGACACCAAGGATAGTGCCCTAAAGGAG"
print(Transcription(t))